##################################################################################################
# UserCenter api
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: usercenter-api
  labels:
    app: usercenter-api
    service: usercenter-api
spec:
  ports:
    - port: 8181
      protocol: TCP
      name: http
  selector:
    app: usercenter-api # 绑定哪个Deployment
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-usercenter-api
  labels:
    account: usercenter-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-api-v1
  labels:
    app: usercenter-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter-api
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: usercenter-api
        version: v1
    spec:
      restartPolicy: Always
      serviceAccountName: cloud-usercenter-api
      containers:
        - name: usercenter-api
          image: registry.cn-hangzhou.aliyuncs.com/mesh-cloud/demo-usercenter-api:v1.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.istio-system.svc.cluster.local:4317
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-api-v2
  labels:
    app: usercenter-api
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercenter-api
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: usercenter-api
        version: v2
    spec:
      restartPolicy: Always
      serviceAccountName: cloud-usercenter-api
      containers:
        - name: usercenter-api
          image: registry.cn-hangzhou.aliyuncs.com/mesh-cloud/demo-usercenter-api:v2.20.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.istio-system.svc.cluster.local:4317
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8181
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
---
##################################################################################################
# Account service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
    service: account-service
spec:
  ports:
    - port: 4001
      protocol: TCP
      targetPort: thrift
  selector:
    app: account-service
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-account-service
  labels:
    account: account-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v1
  labels:
    app: account-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: account-service
        version: v1
    spec:
      restartPolicy: Always
      serviceAccountName: cloud-account-service
      containers:
        - name: account-service
          image: registry.cn-hangzhou.aliyuncs.com/mesh-cloud/demo-services-account:v1.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.istio-system.svc.cluster.local:4317
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 4001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-v2
  labels:
    app: account-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: account-service
        version: v2
    spec:
      restartPolicy: Always
      serviceAccountName: cloud-account-service
      containers:
        - name: account-service
          image: registry.cn-hangzhou.aliyuncs.com/mesh-cloud/demo-services-account:v2.20.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.istio-system.svc.cluster.local:4317
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 4001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
---
