// Code generated by hertz generator.

package handlers

import (
	"context"
	"os"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "pong " + os.Getenv("OTEL_RESOURCE_ATTRIBUTES"),
	})
}
