// Code generated by hertz generator.

package router

import (
	"example.com/apis/usercenter/handlers"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// Register registers customize routers.
func Register(r *server.Hertz) {
	r.GET("/ping", handlers.Ping)

	r.POST("/user.get", handlers.UserGet)
}
