FROM golang:1.19 AS builder

MAINTAINER BoolDesign "booldesign@163.com"

LABEL stage=gobuilder

ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.cn,direct

# RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

COPY go.mod ./
COPY go.mod ./

RUN go mod download && go mod verify

COPY . .

RUN go build -ldflags="-s -w" -o /app/apis-usercenter main.go


FROM centos

ENV TZ Asia/Shanghai

WORKDIR /app

COPY --from=builder /app/apis-usercenter /app/apis-usercenter

EXPOSE 8100

CMD ["./apis-usercenter"]
