// Code generated by hertz generator.

package main

import (
	"example.com/apis/usercenter/router"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
)

func main() {

	options := localOption()
	h := server.Default(options...)

	router.Register(h)
	h.Spin()

}

func localOption() []config.Option {
	return []config.Option{server.WithHostPorts(":8181")}
}
